### ISSUE TITLE
Modsecurity CRS is expecting a missing file

### ISSUE THREAD

**Issue by b0z02003** [coreruleset/modsecurity-crs-docker#72]
Starting from yesterday, `owasp/modsecurity-crs:nginx-alpine` refuses to start when using a simple Nginx configuration such as: 
```
modsecurity on;
modsecurity_rules_file /etc/modsecurity.d/setup.conf;
```
The reason seams to be that `/etc/modsecurity.d/setup.conf` is expecting a file named `/etc/modsecurity.d/modsecurity-override.conf` that is missing.

**Comment by theseion** [comment]
Thanks for reporting this. It could be related to https://github.com/coreruleset/modsecurity-crs-docker/issues/71. We'll look into it.

**Comment by theseion** [comment]
An issue with the image was fixed in https://github.com/coreruleset/modsecurity-crs-docker/issues/62. Can you try force pulling the image?

**Comment by b0z02003** [comment]
Unfortunately, the problem still seems to exists, here is the content of the `/etc/modsecurity.d` directory with a fresh image:

```
/etc/modsecurity.d # ls -al
total 80
drwxrwxr-x    1 root     root          4096 Apr 15 15:54 .
drwxr-xr-x    1 root     root          4096 Apr 15 15:54 ..
-rw-rw-r--    1 root     root         10667 Apr 11 12:50 modsecurity.conf
lrwxrwxrwx    1 root     root            14 Apr 12 12:29 owasp-crs -> /opt/owasp-crs
-rw-r--r--    1 root     root           693 Apr 15 15:54 setup.conf
-rw-rw-r--    1 root     root         53146 Apr 11 12:50 unicode.mapping
```

**Comment by theseion** [comment]
Thanks for checking. We'll investigate.

**Comment by theseion** [comment]
@fzipi I think we forgot to apply the same logic as we did for the `modsecurity-docker` images to the `modsecurity-docker-crs` images. The `docker-entrypoint.sh` file in `modsecurity-docker-crs` replaces the one from the upstream image. None of the scripts in `/docker-entrypoint.d` are being run because of this.
